[platformio]
default_envs = nano_sender

[env]
platform = atmelavr
framework = arduino
monitor_speed = 9600
lib_ldf_mode = chain+
build_flags =
  -DSERIAL_BAUD=9600

[env:nano_sender]
board = nanoatmega328
build_src_filter =
  +<sender_nano/>
  -<receiver_uno/>

[env:uno_receiver]
board = uno
build_src_filter =
  +<receiver_uno/>
  -<sender_nano/>

[env:nano_sender_4800]
extends = env:nano_sender
monitor_speed = 4800
build_flags =
  -DSERIAL_BAUD=4800

[env:nano_sender_9600]
extends = env:nano_sender
monitor_speed = 9600
build_flags =
  -DSERIAL_BAUD=9600

[env:nano_sender_19200]
extends = env:nano_sender
monitor_speed = 19200
build_flags =
  -DSERIAL_BAUD=19200

[env:uno_receiver_4800]
extends = env:uno_receiver
monitor_speed = 4800
build_flags =
  -DSERIAL_BAUD=4800

[env:uno_receiver_9600]
extends = env:uno_receiver
monitor_speed = 9600
build_flags =
  -DSERIAL_BAUD=9600

[env:uno_receiver_19200]
extends = env:uno_receiver
monitor_speed = 19200
build_flags =
  -DSERIAL_BAUD=19200

[env:native]
platform = native
framework =
lib_ldf_mode = chain+
build_flags =
  -Itest
